Repository puzpuzpuz/xsync, pull requests merged in 2021-08, with the labels that each got.

#6 Support nil values in Map
  README.md
  map.go
  map_test.go
Labels: enhancement

#10 Fix sync.Cond misuse in Map resize
  map.go
Labels: bugfix

#9 feature: added support for every builtin concrete type with faster memory hash.
  map.go
  map_test.go
  util.go
Labels: enhancement

#11 Add Map shrinking
  export_test.go
  map.go
  map_test.go
  util.go
Labels: enhancement

#12 Remove string key allocations in Map benchmarks
  map_test.go
Labels: enhancement, benchmark

#13 Clean up Map.Range code
  map.go
Labels: cleanup

#14 Replace FNV-1a with memhash in Map
  README.md
  counter.go
  map.go
  rbmutex.go
  util.go
Labels: enhancement

#15 Fix README MPMCQueue example
  README.md
Labels: documentation, bugfix

#16 Add readme badges
  README.md
Labels: documentation, enhancement

#19 Improve code samples
  README.md
Labels: documentation, enhancement

#20 Add coverage report
  .github/workflows/coverage.yml
  map_test.go
Labels: enhancement

#21 Add coverage badge
  .github/workflows/coverage.yml
  README.md
Labels: enhancement

#22 Add more tests
  export_test.go
  map_test.go
  mpmcqueue_test.go
Labels: enhancement, tests

#23 Fix deadlock in Map.LoadOrStore
  map.go
  map_test.go
Labels: bugfix

#30 Clean up tests
  map_test.go
  mpmcqueue_test.go
Labels: cleanup, tests
