Repository puzpuzpuz/xsync, pull requests merged in 2022-10, with the labels that each got.

#48 Combine top hash caching with bucket chaining
  export_test.go
  map.go
  map_test.go
  mapof.go
  mapof_test.go
  mpmcqueue.go
Labels: cleanup

#49 Support arbitrary comparable keys in MapOf
  README.md
  counter.go
  export_mapof_test.go
  mapof.go
  mapof_test.go
  rbmutex.go
  util.go
Labels: enhancement

#50 Add LoadOrCompute method to Map and MapOf
  map.go
  map_test.go
  mapof.go
  mapof_test.go
Labels: enhancement

#51 Expose built-in string hash function
  map.go
  mapof.go
  util.go
Labels: enhancement

#52 Reduce map bucket size to 1CL
  .github/workflows/build-1.17.yml
  .github/workflows/build-32-bit.yml
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  map.go
  map_test.go
Labels: enhancement

#53 Upgrade GHA actions to v3
  .github/workflows/build-1.17.yml
  .github/workflows/build-32-bit.yml
  .github/workflows/build.yml
  .github/workflows/coverage.yml
Labels: cleanup

#54 Use all available bits in map top hashes
  map.go
  map_test.go
Labels: cleanup

#55 Simplify top hash functions in map
  map.go
  map_test.go
Labels: cleanup

#56 Use hash/maphash instead of go:linkname hacks
  example_test.go
  map.go
  mapof.go
  mapof_test.go
  util.go
Labels: enhancement, cleanup

#57 Rotate seed on map resize
  counter.go
  example_test.go
  map.go
  mapof.go
  rbmutex.go
  util.go
Labels: enhancement

#58 Improve map examples
  README.md
  example_test.go
Labels: documentation, cleanup

#59 Update readme
  BENCHMARKS.md
  README.md
Labels: documentation

#61 Update version in package name
  counter_test.go
  example_test.go
  go.mod
  map_test.go
  mapof_test.go
  mpmcqueue_test.go
  rbmutex_test.go
Labels: bug

#62 Add parallel resize tests for Map and MapOf
  map_test.go
  mapof_test.go
Labels: tests

#63 Fix duplicate keys on intensive map insertion and deletion
  map.go
  map_test.go
  mapof.go
  mapof_test.go
Labels: bug

#64 Add Clear method to Map and MapOf
  map.go
  map_test.go
  mapof.go
  mapof_test.go
Labels: enhancement

#67 Improve map Range benchmarks
  map_test.go
Labels: benchmark

#68 Load and compute
  example_test.go
  map_test.go
  mapof.go
  mapof_test.go
Labels: enhancement

#69 Add Compute method to Map
  counter_test.go
  example_test.go
  map.go
  map_test.go
  mapof.go
  mapof_test.go
  mpmcqueue_test.go
Labels: enhancement

#71 Optimize Counter thread-to-stripe distribution
  README.md
  counter.go
  counter_test.go
  rbmutex.go
  util.go
Labels: enhancement

#72 Improve Map and MapOf godoc
  README.md
  map.go
  mapof.go
Labels: documentation, cleanup

#74 Fix out of range error in Counter on GOMAXPROCS change
  counter.go
  counter_test.go
Labels: bugfix, cleanup

#76 Optimize MapOf integer hash function
  map.go
  map_test.go
  mapof.go
  mapof_test.go
  util.go
Labels: performance

#75 Optimize RBMutex footprint and thread-to-slot distribution
  BENCHMARKS.md
  README.md
  counter.go
  rbmutex.go
  rbmutex_test.go
Labels: enhancement

#77 Fix hashUint64 function godoc
  util.go
Labels: cleanup
