Repository puzpuzpuz/xsync, pull requests merged in 2023-06, with the labels that each got.

#98 Fix nextPowOf2 on zero input
  util.go
  util_test.go
Labels: bugfix

#99 Improve test consistency
  export_test.go
  util_test.go
Labels: cleanup

#101 Mention v1 as discontinued version in readme
  README.md
Labels: documentation
