Repository puzpuzpuz/xsync, pull requests merged in 2024-07, with the labels that each got.

#134 WIP better MapOf
  BENCHMARKS.md
  README.md
  export_test.go
  map.go
  mapof.go
  mapof_test.go
  util.go
  util_test.go
Labels: enhancement, performance

#137 Add NewMapOfWithHasher function
  export_test.go
  mapof.go
  mapof_test.go
  util_hash.go
  util_hash_test.go
Labels: performance

#139 Fix Map/MapOf capacity calculation for WithPresize
  README.md
  map.go
  map_test.go
  mapof.go
  mapof_test.go
Labels: bug

#138 Add RBMutex.TryRLock
  rbmutex.go
Labels: enhancement
