Repository puzpuzpuz/xsync, pull requests merged in 2025-05, with the labels that each got.

#168 New data structure: UMPSCQueue
  umpscqueue.go
  umpscqueue_test.go
Labels: enhancement

#171 Tweak UMPSCQueue documentation and tests
  README.md
  counter.go
  map.go
  mpmcqueue.go
  mpmcqueue_test.go
  rbmutex.go
  spscqueue.go
  spscqueue_test.go
  umpscqueue.go
  umpscqueue_test.go
Labels: documentation, cleanup

#170 Parallel Map resize
  map.go
Labels: enhancement, performance

#172 Add documentation for parallel Map resize
  README.md
  map.go
  map_test.go
Labels: documentation
